language: php

sudo: false

php:
  - 7.0
  - 7.1
  - 7.2

before_script:
  - composer self-update
  - composer install
  - wget https://scrutinizer-ci.com/ocular.phar
  - mysql -e 'CREATE DATABASE lmk_test;'
  - php artisan migrate --force

script:
 - mkdir -p build/logs
 - phpunit --coverage-clover build/logs/clover.xml

after_script:
 - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml